### ISSUE TITLE
路由中alwaysShow作用没太明白

### ISSUE THREAD

**Issue by lolicrafter** [un-pany/v3-admin#5]
>   // 当一个路由下面的 children 声明的路由大于1个时，自动会变成嵌套的模式
>   // 只有一个时，会将那个子路由当做根路由显示在侧边栏
>  // 若想不管路由下面的 children 声明的个数都显示你的根路由
> // 可以设置alwaysShow: true，这样就会忽略之前定义的规则，一直显示根路由
> alwaysShow: true

看文档我以为是把根路由下的子路由放到侧边栏,和监控,权限管理菜单同级别显示,但是设置了true和false都没变.
没办法实现,我又自己写了代码实现的.
```html
    <template v-if="!alwaysShowRootMenu && theOnlyOneChild && !theOnlyOneChild.children">
       <SidebarItemLink v-if="theOnlyOneChild.meta" :to="resolvePath(theOnlyOneChild.path)">
        <!-- 原代码 -->
      </SidebarItemLink>
    </template>

    <template v-else>
      <template v-if="!alwaysShowRootMenu && childrenShowOut">
        <SidebarItemLink v-for="child in childrenShowOut" :key="child?.path" :to="resolvePath(child?.path)">
           <!-- 原代码 -->
        </SidebarItemLink>
      </template>
      <el-sub-menu v-else :index="resolvePath(item.path)" popper-append-to-body>
        <!-- 原代码 -->
      </el-sub-menu>
    </template>
```

```js
const childrenShowOut = computed(() => {
  if (showingChildNumber.value <= 1) {
    return null
  }
  // 把根目录下的路由提取到一级菜单
  if (props.item.path !== '/') return null
  if (props.item.children) {
    return props.item.children.filter(item => {
      return item
    })
  }
  return { ...props.item, path: '' }
})
```

ts我不熟,` v-for="child in childrenShowOut"` 会报警告,不知道怎么解决....

**Comment by pany-ang** [comment]
![SXHJPL J)CR WDA8 YLPXV2](https://user-images.githubusercontent.com/49087880/158048584-da177e09-69d8-49d0-bbd4-ff41b4b9960e.png)
![9~23)V B{{GFW4AG4M~COF8](https://user-images.githubusercontent.com/49087880/158048587-7009e300-fdc8-4897-aafc-60902bded30c.png)

**Comment by pany-ang** [comment]
默认情况下，如果 children 下只有一个子路由，那么就不会显示父路由。如果这种情况下要显示父路由，那么要在父路由设置 alwaysShow: true

**Comment by lolicrafter** [comment]
> 

大佬好,我是想把 **'/'根路径**的父路由隐藏,只显示里面的子路由(**数量大于1**).
就如图上的,不显示'测试',只显示首页等等...如图,想要这样的效果.⬇
![路由](https://user-images.githubusercontent.com/98165056/160514811-cf651bc4-aebb-4468-b9b3-7c0f1795ae46.png)
____________
目前只能每次都要把单独一个路由放到Layout的children里面才能实现这样的效果.

**Comment by pany-ang** [comment]
那是肯定。但是你为什么要把这些看着像同级的路由，放到根路由的 children 里呢，感觉不必这么做

**Comment by lolicrafter** [comment]
> 
因为我想要打开新标签的时候左侧菜单栏一直存在,
不然的话打开一个路由就变成这样了
![路由2](https://user-images.githubusercontent.com/98165056/160529937-903562da-c6de-43a3-973e-af410ee11bda.png)
![路由3](https://user-images.githubusercontent.com/98165056/160529938-6eb95e6a-a4d5-4d3d-b2fa-16d4b3eb00b1.png)

**Comment by pany-ang** [comment]
你并没有找到正确是使用方法...

你像这样新增路由，不就可以解决你的问题了吗？

```
{
    path: '/tag',
    component: Layout,
    redirect: '/tag/index',
    children: [
      {
        path: 'index',
        component: () => import(/* webpackChunkName: "tag" */ '@/views/tag/index.vue'),
        name: 'Tag',
        meta: {
          title: 'tag',
          icon: 'tag'
        }
      }
    ]
  },
```

**Comment by pany-ang** [comment]
并不是像你这样全部都添加到根路由的 children。children 明显是子路由的意思，不是用来存放同级路由的

**Comment by lolicrafter** [comment]
> 你并没有找到正确是使用方法...
> 
> 你像这样新增路由，不就可以解决你的问题了吗？
> 
> ```
> {
>     path: '/tag',
>     component: Layout,
>     redirect: '/tag/index',
>     children: [
>       {
>         path: 'index',
>         component: () => import(/* webpackChunkName: "tag" */ '@/views/tag/index.vue'),
>         name: 'Tag',
>         meta: {
>           title: 'tag',
>           icon: 'tag'
>         }
>       }
>     ]
>   },
> ```

但是这样每次都要新增路由,然后再添加到children里面.
我想直接放到根路由里省事了.

**Comment by pany-ang** [comment]
好吧，那就只能根据自己需求去修改源码逻辑了
