### ISSUE TITLE
第二次请求/users/info接口会报跨域错误

### ISSUE THREAD

**Issue by NingYuanLin** [un-pany/v3-admin#7]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/57001533/161430912-cb3d7662-f9c7-4f45-87a1-2594c1c67cb3.png">
登录的时候会请求一次/users/info接口，此时是没问题的，但是我登录上以后，如果再刷新一次页面，还会请求/users/info接口，此时就会报跨域错误，并且我仔细对照了options请求，发现参数是一模一样的。

第一次option：
<img width="593" alt="image" src="https://user-images.githubusercontent.com/57001533/161431184-63bb48e7-1947-45a1-bb5f-e416009b8594.png">
第一次post：
<img width="601" alt="image" src="https://user-images.githubusercontent.com/57001533/161431202-2539fe6b-d673-4b9b-baf1-3aa76aedd25d.png">
第二次option:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/57001533/161431222-d777ffc1-e9b3-4813-b6ea-26567d1bfcf7.png">
第二次post:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/57001533/161431230-cb4da309-04b2-40fe-86d7-ff83e93c403e.png">

**Comment by NingYuanLin** [comment]
第二次options请求，我的后端监听到的请求是：`{}options`，前面不知为何多了个`{}`:
```
127.0.0.1 - - [03/Apr/2022 21:44:58] "{}OPTIONS /users/info HTTP/1.1" 405 -
```
这是第一次options:
```
127.0.0.1 - - [03/Apr/2022 21:44:47] "OPTIONS /users/info HTTP/1.1" 200 -
```

**Comment by pany-ang** [comment]
我不能复现，这应该不是前端的问题，检查后端的 CORS 配置，或用反向代理试试

**Comment by NingYuanLin** [comment]
好的谢谢，我再仔细检查一下
