### ISSUE TITLE
脚手架不是vite吗？

### ISSUE THREAD

**Issue by airzhanglin** [un-pany/v3-admin#8]
脚手架不是vite吗？

**Comment by pany-ang** [comment]
vue-cli 5.x

**Comment by xdmrpgy** [comment]
感觉框架代码清新简洁，没有过度封装，非常容易上手使用。就有两点小小建议：
1、目前vite构建更快速，基本要取代vue-cli成为官方脚手架了，请问什么时候能迁移到vite呢？
2、能否增加一些示例，比如一个简单的字典管理，对表格的增删改查、导出、跳转详情页等操作。

**Comment by pany-ang** [comment]
> 框架代码清新明亮，没有过度使用，非常容易上手使用。 1、当前vite的脚架比较快，基本要推荐vue-cli成为官方手把手了，请问什么时候能迁移到感觉了2 、增加操作页等可以增加一些示例，例如，对表格的简单修改改查、导出、跳转详情。

谢谢。确实会考虑 vite 的。但是示例暂时不打算写，这个仓库是想单纯拿来给大家做二次开发的，当然如果有特别好的CRUD实践，也会考虑写上去做个参考

**Comment by pany-ang** [comment]
> 脚手架不是vite吗？

https://github.com/un-pany/v3-admin-vite 写了一个 vite 版本

**Comment by pany-ang** [comment]
> https://github.com/un-pany/v3-admin-vite 写一个 vite 版本

https://github.com/un-pany/v3-admin-vite 写了一个 vite 版本

**Comment by pany-ang** [comment]
> 感觉框架代码清新简洁，没有过度封装，非常容易上手使用。就有两点小小建议： 1、目前vite构建更快速，基本要取代vue-cli成为官方脚手架了，请问什么时候能迁移到vite呢？ 2、能否增加一些示例，比如一个简单的字典管理，对表格的增删改查、导出、跳转详情页等操作。

https://github.com/un-pany/v3-admin-vite 写了一个 vite 版本
